baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'DoIt'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.page.comment]
  enable = true
[params.page.comment.giscus]
  # You can refer to the official documentation of giscus to use the following configuration.
  # 你可以参考官方文档来使用下列配置
  enable = true
  repo = "yizt/discussions"
  repoId = "R_kgDOQNTuVA"
  category = "Announcements"
  categoryId = "DIC_kwDOQNTuVM4CxVOc"
  mapping = "pathname"
