baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'dream'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.giscus]
  data-repo="yizt/discussions"
  data-repo-id="R_kgDOQNTuVA"
  data-category="Announcements"
  data-category-id="DIC_kwDOQNTuVM4CxVOc"
  data-mapping="pathname"
  data-strict="0"
  data-reactions-enabled="1"
  data-emit-metadata="0"
  data-input-position="top"
  data-theme="preferred_color_scheme"
  data-lang="zh-CN"
  data-loading="lazy"
  crossorigin="anonymous"